<?php  namespace JoaoJoyce\Phlatdb\Eloquent;

use Illuminate\Database\Query\Builder;
use JoaoJoyce\Phlatdb\Phlatdb;

class QueryBuilder extends Builder {

    private $phlatdb;

    public function __construct(Phlatdb $phlatdb)
    {
        $this->phlatdb = $phlatdb;
    }


    public function all($columns = ['*']) {


        return $this->phlatdb->all();

    }


    public function get($columns = ['*']) {
        return $this->phlatdb->get();
    }

    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {
        return $this->phlatdb->where($column, $operator, $value, $boolean); // TODO: Change the autogenerated stub
    }

    public function orderBy($column, $direction = 'asc') {
        return $this->phlatdb->orderBy($column,$direction);
    }

    public function insertGetId(array $values, $sequence = null)
    {
        $keys = $this->phlatdb->insert($values)->save();
        if(count($keys)==1) {
            return $keys[0];
        }
    }

}
 